# Generated by Django 4.0.5 on 2022-06-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=100)),
                ('order_price', models.FloatField()),
                ('order_menu', models.CharField(max_length=100)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.table')),
            ],
        ),
    ]
